// Vehicle data for the Heavy Tech AI Vision Dashboard
const vehicleData = [
    {
        id: 1,
        name: "Heavy Tech Skid Loader",
        type: "Skid Loader",
        image: "vehicle-sample-image.png",
        isActive: true,
        batteryHealth: "98%",
        chargeRate: "22kW, 3.2hrs",
        torqueSplit: "70% Battery, 30% ICE",
        driveMode: "Normal",
        location: {
            coordinates: "40.7128° N, 74.0060° W",
            address: "Construction Site A, Manhattan, NY",
            zone: "Zone 7 - Main Operations"
        },
        powerStatus: true,
        connectionStatus: "Connected",
        dataStatus: "Live",
        aiVizStatus: "Active",
        operationalHours: "247.5 hrs",
        fuelLevel: "85%",
        hydraulicPressure: "2,400 PSI",
        engineTemp: "182°F",
        operatorId: "OPR-001",
        lastMaintenance: "2024-01-15",
        nextMaintenance: "2024-04-15",
        alerts: [],
        efficiency: "94%",
        workMode: "Standard Operations",
        attachments: ["Standard Bucket", "Hydraulic Breaker"],
        serialNumber: "HT-SL-2024-001"
    },
    {
        id: 2,
        name: "Heavy Tech Excavator",
        type: "Excavator",
        image: "vehicle-sample-image.png",
        isActive: false,
        batteryHealth: "92%",
        chargeRate: "15kW, 4.1hrs",
        torqueSplit: "60% Battery, 40% ICE",
        driveMode: "Eco",
        location: {
            coordinates: "40.7580° N, 73.9855° W",
            address: "Construction Site B, Central Park, NY",
            zone: "Zone 3 - Excavation"
        },
        powerStatus: false,
        connectionStatus: "Connected",
        dataStatus: "Live",
        aiVizStatus: "Standby",
        operationalHours: "189.2 hrs",
        fuelLevel: "72%",
        hydraulicPressure: "3,200 PSI",
        engineTemp: "175°F",
        operatorId: "OPR-002",
        lastMaintenance: "2024-01-10",
        nextMaintenance: "2024-04-10",
        alerts: ["Hydraulic fluid low"],
        efficiency: "88%",
        workMode: "Precision Digging",
        attachments: ["Digging Bucket", "Thumb Attachment"],
        serialNumber: "HT-EX-2024-002"
    },
    {
        id: 3,
        name: "Heavy Tech Bulldozer",
        type: "Bulldozer",
        image: "vehicle-sample-image.png",
        isActive: false,
        batteryHealth: "89%",
        chargeRate: "25kW, 2.8hrs",
        torqueSplit: "50% Battery, 50% ICE",
        driveMode: "Heavy",
        location: {
            coordinates: "40.7831° N, 73.9712° W",
            address: "Construction Site C, Upper West Side, NY",
            zone: "Zone 1 - Earthmoving"
        },
        powerStatus: true,
        connectionStatus: "Connected",
        dataStatus: "Live",
        aiVizStatus: "Active",
        operationalHours: "301.7 hrs",
        fuelLevel: "91%",
        hydraulicPressure: "2,800 PSI",
        engineTemp: "195°F",
        operatorId: "OPR-003",
        lastMaintenance: "2024-01-05",
        nextMaintenance: "2024-04-05",
        alerts: ["Scheduled maintenance in 15 days"],
        efficiency: "91%",
        workMode: "Heavy Earthmoving",
        attachments: ["Straight Blade", "Ripper"],
        serialNumber: "HT-BD-2024-003"
    },
    {
        id: 4,
        name: "Heavy Tech Wheel Loader",
        type: "Wheel Loader",
        image: "vehicle-sample-image.png",
        isActive: false,
        batteryHealth: "95%",
        chargeRate: "18kW, 3.8hrs",
        torqueSplit: "75% Battery, 25% ICE",
        driveMode: "Boost",
        location: {
            coordinates: "40.7505° N, 73.9934° W",
            address: "Construction Site D, Midtown, NY",
            zone: "Zone 5 - Material Handling"
        },
        powerStatus: false,
        connectionStatus: "Weak Signal",
        dataStatus: "Intermittent",
        aiVizStatus: "Offline",
        operationalHours: "156.3 hrs",
        fuelLevel: "68%",
        hydraulicPressure: "2,600 PSI",
        engineTemp: "178°F",
        operatorId: "OPR-004",
        lastMaintenance: "2024-01-20",
        nextMaintenance: "2024-04-20",
        alerts: ["Communication issue", "GPS signal weak"],
        efficiency: "87%",
        workMode: "Material Loading",
        attachments: ["General Purpose Bucket", "Pallet Forks"],
        serialNumber: "HT-WL-2024-004"
    },
    {
        id: 5,
        name: "Heavy Tech Compact Excavator",
        type: "Compact Excavator",
        image: "vehicle-sample-image.png",
        isActive: false,
        batteryHealth: "87%",
        chargeRate: "12kW, 4.5hrs",
        torqueSplit: "80% Battery, 20% ICE",
        driveMode: "Eco",
        location: {
            coordinates: "40.7282° N, 73.9942° W",
            address: "Construction Site E, Greenwich Village, NY",
            zone: "Zone 8 - Utility Work"
        },
        powerStatus: true,
        connectionStatus: "Connected",
        dataStatus: "Live",
        aiVizStatus: "Active",
        operationalHours: "203.8 hrs",
        fuelLevel: "79%",
        hydraulicPressure: "2,200 PSI",
        engineTemp: "172°F",
        operatorId: "OPR-005",
        lastMaintenance: "2024-01-25",
        nextMaintenance: "2024-04-25",
        alerts: [],
        efficiency: "96%",
        workMode: "Utility Installation",
        attachments: ["Narrow Bucket", "Auger"],
        serialNumber: "HT-CE-2024-005"
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = vehicleData;
} 